### ISSUE TITLE
REQUEST: Make overlay scalable and not interfere with map movement

### ISSUE THREAD

**Issue by GambetTV** [xaukael/token-talk#1]
Love the module! Would it be possible to make the chat bubble scale with the grid size? Right now if I set my grid size to 50 pixels or 200 pixels the chat bubble remains the same, which at 200 is kinda small and at 50 is comically large.

Also for whatever reason if your mouse is on top of the chat bubble and you try to scroll in or out with mouse wheel it interferes with it, any way you could fix that?

Thanks!

**Comment by xaukael** [comment]
I will be able to do the grid scaling easy enough. 
I have pointer events on the bubble so that you can remove it by clicking it. This causes the scroll event to be captured as well. I can either take away the click to delete option, or learn to live with the scroll zoom interference.
